openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
paths:
  /api/orders:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid order data
  /api/orders/{id}:
    get:
      summary: Get an order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
components:
  schemas:
    LineItem:
      type: object
      properties:
        itemId:
          type: integer
        itemPrice:
          type: number
          format: double
        itemQuantity:
          type: integer
    Order:
      type: object
      properties:
        id:
          type: integer
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        totalAmount:
          type: number
          format: double
        status:
          type: string
          enum: [RECEIVED, REJECTED, ACCEPTED]