openapi: 3.1.0
info:
  title: RAG Plugin
  description: A plugin for answering questions using RAG (Retrieve, Augment, Generate) on data indexed by Azure AI Search.
  version: 'v1'
servers:
  - url: http://localhost:7071
paths:
  /ask:
    post:
      operationId: askFunction
      description: |
        Ask a question to the indexed information.
        e.g. {"query": "Tell me about our health benefits."}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/askFunctionRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    askFunctionRequest:
      type: object
      properties:
        query:
          type: string
      required:
        - query