name: Deploy to razopenai-orchestrator

# Run the workflow whenever change is pushed into the main branch.
# You can also trigger the workflow manually by clicking the Run workflow button under the Actions tab in your repository
on:
  push:
    branches: [ main ]
    paths:
      - 'LangChain/orchestrator-azure-search-chatmodelonly-mongodb-memory'
      - '.github/workflows/deploy_search_orchestrator.yml'
  workflow_dispatch:      

env:
  PYTHON_VERSION: '3.11'
  WORKING_DIRECTORY: 'LangChain/orchestrator-azure-search-chatmodelonly-mongodb-memory'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: python -m pip install --upgrade pip

      - name: Create and start virtual environment
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: pip install -r requirements.txt

      - name: Archive artifact for deployment
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          rm -rf venv
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: ${{ env.WORKING_DIRECTORY }}/release.zip
  
  # Deploy the application to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
      
      - name: Extract artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name:
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_RAZOPENAI_ORCHESTRATOR_PUBLISHPROFILE }}